# Sensiolabs Insight configuration

global_exclude_dirs:
    - vendor
    - web
    - docker
    - bin

pre_composer_script: |
    #!/bin/bash

    cp app/config/parameters.yml.dist app/config/parameters.yml

exclude_patterns:
    - app/autoload.php
    - app/check.php
    - app/SymfonyRequirements.php

rules:
    symfony.web_config_should_not_be_present:
        enabled: false