version: '2'

services:
    gitcolab:
        build: ./docker/app
        depends_on:
            - app_db
    nginx:
        ports:
            - "86:80"
        image: nginx
        depends_on:
            - php_fpm
        labels:
            - "traefik.backend=gitcolab"
            - "traefik.frontend.rule=Host:${SITE_HOST}"
            - "traefik.port=80"
            - "traefik.frontend.passHostHeader=true"
        volumes_from:
            - php_fpm
        volumes:
           - ./docker/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
           - ./:/opt/gitcolab
           - ./var/logs/nginx/:/var/log/nginx

    php_fpm:
        build: ./docker/php
        depends_on:
            - app_db
        expose:
            - "9000"
        volumes:
            - ./:/opt/gitcolab

    app_db:
        image: mariadb
        environment:
            MYSQL_USER: gitcolab
            MYSQL_PASSWORD: azerty123
            MYSQL_ROOT_PASSWORD: azerty123
            MYSQL_DB: gitcolab

        labels:
            - "traefik.enable=false"
