version: '3'

networks:
  proxy:
    external: true

services:
    nginx:
        image: nginx
        depends_on:
            - php
        labels:
            - "traefik.backend=gitcolab"
            - "traefik.frontend.rule=Host:${SITE_HOST-gitcolab.localhost}"
            - "traefik.http.routers.nginx.rule=Host(`${SITE_HOST-gitcolab.localhost}`)"
            - "traefik.port=80"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.docker.network=proxy"
        volumes:
           - ./docker/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
           - ./:/opt/gitcolab
           - ./var/log/nginx/:/var/log/nginx

    php:
        build: ./docker/php
        depends_on:
            - postgresql
        volumes:
            - ./:/opt/gitcolab

    postgresql:
        image: postgres:11.5
        environment:
            POSTGRES_USER: gitcolab
            POSTGRES_PASSWORD: azerty123
            POSTGRES_ROOT_PASSWORD: azerty123
            POSTGRES_DB: gitcolab
        labels:
            - "traefik.enable=false"
        ports:
            - 50432:5432
