imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: resource.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        gitcolab:
          url: %gitcolab.url%
    form:
        resources: ['bootstrap_3_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    StofDoctrineExtensionsBundle: true
                    GitcolabAppBundle:
                        prefix: Gitcolab\Bundle\AppBundle\Model
                        dir: "%kernel.root_dir%/../src/Gitcolab/Bundle/AppBundle/Model/"
                        type: xml

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            timestampable: true
            sluggable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# REST Configuration
fos_rest:
    allowed_methods_listener: true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    format_listener:
        media_type:
            version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'
        rules:
            -
                path: '^/api'
                priorities: ['application/json', '*/*']
                fallback_format: json
                prefer_extension: true
            -
                path: '^/'
                priorities: [ 'text/html', '*/*']
                fallback_format: html
                prefer_extension: true
    param_fetcher_listener: true
    routing_loader:
        default_format: html
        include_format: false
    view:
        serialize_null: true
        view_response_listener: force
        mime_types:
            json:
                - 'application/json'
                - 'application/vnd.api+json'
        formats:
            xml: false
            json: true
            html: true

jms_serializer:
    metadata:
        auto_detection: true

gitonomy_git:
    profiler: true
    twig_extension:
        enabled: true
        routes_names:
            tree: project_tree
            commit: project_commit
        themes:
            - GitcolabAppBundle:Git:theme.html.twig
            - GitonomyGitBundle::default_theme.html.twig


gitcolab_app:
    repository_path: %gitcolab.repository_path%
    ssh_host: %gitcolab.ssh_host%
    # ssh_host: ssh.host_example.com
    user:  %gitcolab.user%
