security:
    encoders:
        Gitcolab\Bundle\AppBundle\Model\User\User:
            algorithm: sha512
            encode_as_base64: true
            iterations: 34

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        main:
            entity:
                class: Gitcolab\Bundle\AppBundle\Model\User\User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
                default_target_path: dashboard
            logout:
                path: logout
                target: login
            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/*, role: ROLE_USER }
