_welcome:
  path: /
  defaults:
      _controller: GitcolabAppBundle:Dashboard:main

user:
  resource: "@GitcolabAppBundle/Resources/config/routing/user.yml"
  prefix: /user

key:
  resource: "@GitcolabAppBundle/Resources/config/routing/key.yml"
  prefix : /key

_keys_api:
  type: rest
  prefix:   /api/{version}/internal/key
  resource: "@GitcolabAppBundle/Resources/config/routing/key_api.yml"
  defaults:
      version: v1