dashboard:
  path: /
  defaults:
      _controller: GitcolabAppBundle:Dashboard:main

user:
  resource: "@GitcolabAppBundle/Resources/config/routing/user.yml"
  prefix: /user

key:
  resource: "@GitcolabAppBundle/Resources/config/routing/key.yml"
  prefix : /key

_keys_api:
  type: rest
  prefix:   /api/{version}/internal/key
  resource: "@GitcolabAppBundle/Resources/config/routing/key_api.yml"
  defaults:
      version: v1

organization:
  resource: "@GitcolabAppBundle/Resources/config/routing/organization.yml"

project:
  resource: "@GitcolabAppBundle/Resources/config/routing/project.yml"
  prefix : /

project_show:
  path: /{slug}
  defaults:
      _controller: GitcolabAppBundle:Project:show
  requirements:
      slug: ".+"

project_setting:
  path: /{slug}/settings
  defaults:
       _controller: GitcolabAppBundle:Project:settings

