Gitcolab\Bundle\AppBundle\Model\User\User:
    exclusion_policy: ALL
    properties :
      id :
        expose : true
      username :
        expose : true
      slug:
        expose : true
      avatar:
        expose : true