milestones:
  path: /{slug}/milestones
  defaults:
      _controller: GitcolabAppBundle:Tracker/Milestone:index
  requirements:
      slug: ".+"

milestone_create:
  path: /{slug}/milestone/new
  defaults:
      _controller: GitcolabAppBundle:Tracker/Milestone:create
  requirements:
      slug: ".+"

milestone_show:
  path: /milestone/{slug}
