user_profile:
    path: /user/profile
    defaults:
        _controller: GitcolabAppBundle:User:profile

user_account:
    path: /account
    defaults:
        _controller: GitcolabAppBundle:User:account

user_keys:
    path: /user/ssh
    defaults:
        _controller: GitcolabAppBundle:Key:ssh

login:
    path: /login
    defaults:
        _controller: GitcolabAppBundle:User/Security:login

login_check:
    path: /login_check

logout:
    path: /logout

user_autocomplete:
    path: /api/{version}/user/autocomplete
    defaults:
        version: 1
        _controller: GitcolabAppBundle:User:autocomplete